apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: <name>
      endpoint: <address>
      access_key: <ak>
      secret_key: <sk>