---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-ds-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-sa-logs-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  # Role or ClusterRole here, depending on which you chose to provision
  kind: Role
  name: namespace-logs-viewer
subjects:
- kind: ServiceAccount
  name: grafana-ds-sa
  namespace: default